version: '3'
services:
  db:
    image: mongo:6
    restart: always
    networks:
      - internal
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  base:
    image: linuxodyssey/quest-base
    networks:
      - players-dev
    build:
      context: .
      dockerfile: ./quests/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
 
networks:
  internal:
  players-dev:
    name: linux-odyssey-players-dev
    internal: false
